import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { formatDateTime, formatDate, formatNumber } from './format';

export function exportChallanPDF(challan) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;

  // Helpers
  const getVal = (val) => val ? val : '-';

  // --- Header ---
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(33, 33, 33);
  doc.text('MAL ERP/CRM', 14, 22);

  doc.setFontSize(16);
  doc.setTextColor(100, 100, 100);
  doc.text('INVOICE', pageWidth - 14, 22, { align: 'right' });

  // Draw a top line
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.5);
  doc.line(14, 28, pageWidth - 14, 28);

  // --- Company Details ---
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(80, 80, 80);
  doc.text('MAL ERP/CRM', 14, 36);
  doc.text('Hyderabad Telangana India', 14, 41);
  doc.text('Phone: +91 9000012345', 14, 46);
  doc.text('Email: info@malerp.com', 14, 51);

  // --- Challan Details ---
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(50, 50, 50);
  doc.text('Challan Details:', pageWidth - 70, 36);
  doc.setFont('helvetica', 'normal');
  doc.text(`Number: ${getVal(challan.challan_number)}`, pageWidth - 70, 41);
  doc.text(`Date: ${formatDate(challan.created_at)}`, pageWidth - 70, 46);
  doc.text(`Status: ${getVal(challan.status).toUpperCase()}`, pageWidth - 70, 51);

  // --- Customer Details ---
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(50, 50, 50);
  doc.text('Billed To:', 14, 65);

  doc.setFont('helvetica', 'normal');
  const cust = challan.customers || {};
  doc.text(`Customer Name: ${getVal(cust.name)}`, 14, 70);
  doc.text(`Business Name: ${getVal(cust.business_name)}`, 14, 75);
  doc.text(`Mobile: ${getVal(cust.mobile)}`, 14, 80);
  doc.text(`Email: ${getVal(cust.email)}`, 14, 85);
  doc.text(`GST Number: ${getVal(cust.gst_number)}`, 14, 90);
  doc.text(`Address: ${getVal(cust.address)}`, 14, 95);

  // --- Products Table ---
  const tableColumn = ["Product", "SKU", "Quantity", "Unit Price", "Total"];
  const tableRows = [];

  let totalAmount = 0;

  if (challan.items && challan.items.length > 0) {
    challan.items.forEach(item => {
      // Handle the snapshot
      const snap = item.product_snapshot || {};
      const name = snap.name || item.products?.name || 'Unknown Product';
      const sku = snap.sku || '-';
      const qty = item.quantity || 0;
      const price = Number(item.unit_price) || Number(snap.unit_price) || 0;
      const lineTotal = qty * price;

      totalAmount += lineTotal;

      tableRows.push([
        name,
        sku,
        formatNumber(qty),
        `$${price.toFixed(2)}`,
        `$${lineTotal.toFixed(2)}`
      ]);
    });
  }

  autoTable(doc, {
    startY: 105,
    head: [tableColumn],
    body: tableRows,
    theme: 'grid',
    headStyles: { fillColor: [50, 50, 50], textColor: 255 },
    styles: { fontSize: 9, cellPadding: 4 },
    columnStyles: {
      2: { halign: 'right' },
      3: { halign: 'right' },
      4: { halign: 'right' }
    }
  });

  // --- Summary Section ---
  const finalY = doc.lastAutoTable.finalY || 105;

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(33, 33, 33);
  doc.text('Summary', pageWidth - 14, finalY + 10, { align: 'right' });

  doc.setFont('helvetica', 'normal');
  doc.text(`Total Quantity: ${formatNumber(challan.total_quantity)}`, pageWidth - 14, finalY + 16, { align: 'right' });
  doc.text(`Total Amount: $${totalAmount.toFixed(2)}`, pageWidth - 14, finalY + 22, { align: 'right' });

  // --- Footer ---
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);

    // Bottom line
    const pageHeight = doc.internal.pageSize.height;
    doc.setDrawColor(200, 200, 200);
    doc.line(14, pageHeight - 15, pageWidth - 14, pageHeight - 15);

    doc.text('Generated by MAL ERP/CRM', 14, pageHeight - 10);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
    doc.text('© 2026 MAL ERP/CRM. All rights reserved.', pageWidth - 14, pageHeight - 10, { align: 'right' });
  }

  // --- Save PDF ---
  const fileName = `challan-${challan.challan_number || 'export'}.pdf`;
  doc.save(fileName);
}
